### ISSUE TITLE
polyglotpkg not installed from mvn package command on polyglot python archetype

### ISSUE THREAD

**Issue by b-mad** [vmware/vrealize-developer-tools#108]
The package execution fails on a new polyglot project. Is there a configuration required to install the polyglotpkg executable on the local system prior?

Steps to reproduce:

1. Create new python based project following https://github.com/vmware/vrealize-developer-tools/wiki/Polyglot-project#create-new-polyglot-project
2. Execute `mvn clean package`

Output:

``` text
> polyglotpkg --env polyglot

sh: polyglotpkg: command not found

...

[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (npm run build - compile) on project demo-polyglot: Command execution failed.: Process exited with an error: 127 (Exit value: 127) -> [Help 1]
```

**Comment by mduchev** [comment]
@b-mad Can you try to execute the command with different type parameter at the end and see if that will fix your issue?  If you want to have a vro package, them add `-Dtype=**vro**`, and if you want to use it as an abx action, then add `-Dtype=**abx**`. There's more information about the issue in the PR that I've created.
