### ISSUE TITLE
Failed to decode passwords when loading settings.xml

### ISSUE THREAD

**Issue by ssnui** [vmware/vrealize-developer-tools#112]
### Description

My organization uses password management that automatically generate and rolls password every week. The password character set includes "<" and ">" which caused error if it's saved to settings.xml. To avoid it, I have to set UTF8Encode to $true in the PS script that I use to automatically update that file, here's the PS snippet:
    $settings = New-Object System.Xml.XmlWriterSettings
    $settings.Encoding = New-Object System.Text.UTF8Encoding( $true )

The VS Code plugin does not decode the password when it reads the settings.xml causing it 
### Steps to Reproduce

1. [First Step]
    Create a password that contains < or > in settings.xml. Save the settings.xml.
2. [Second Step]
    Run VSCode
3. The data for vRO system does not load

**Expected behavior:** It should connect without problem if the password is decoded

**Actual behavior:** [What actually happens]

**Reproduces how often:** 100%

#### Client

-   vRealize Developer Tools Version:
-   vRealize Build Tools Version:
-   Visual Studio Code Version:
-   OS Version:

#### Server

-   vRealize Automation Version: 7.x, 8x
-   vRealize Orchestrator Version: 7.x, 8.x

**Comment by joroaf** [comment]
Hi @ssnui,

I would suggest you use encrypted passwords (see: https://maven.apache.org/guides/mini/guide-encryption.html):

1. It will improve your security posture
2. It will workaround your problem

Cheers!

**Comment by ssnui** [comment]
Hi @joroaf,
It didn't work at all as I follow the MVN encryption guide. Got error 401 when I use encrypted password, if I use the provided password it worked fine. I tried to test the mvn --encrypt-password command, I got 10 different results LOL! That explains why it got error 401 since I believe it did not decrypt the password correctly.
It's one line of code and it does not affect anything else even the current code flow. If you don't want to do it, I can submit a pull request and add it.

BTW, can you provided a working vRO 8 config for the settings.xml since I can't get it working at all. All vRO 7 works fine (if the password does not contain < or >).
Thanks,
   - ssnui

![mvn-encrypt](https://user-images.githubusercontent.com/11965827/191301792-f210e717-49c7-4626-8e60-8aa34b3688a2.PNG)

**Comment by Michaelpalacce** [comment]
Hey @ssnui! 

A few notes:

1. When you run the mvn --encrypt-password, the password generated is expected to be different every time, that's ok.
2. If you wish to use encrypted maven credentials, you have to put them in the "servers" section in your settings.xml


A working settings.xml ( truncated ) would look like this (notice the "vro.serverId" and "vrang.serverId" pointing to an id that is present in my "servers" section):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">
    <servers>
        <server>
            <id>vro</id>
            <username>configurationadmin@System Domain</username>
            <password>{5a593XJmccIHejrppq19g1VIqtn3I34KFryPXJ7mhaw=}</password>
        </server>
    </servers>
    <profiles>
      .......
        <profile>
            <id>DevLab</id>
            <properties>
                <vro.host>vra-l-01a.corp.local</vro.host>
                <vro.port>443</vro.port>
                <vro.serverId>vro</vro.serverId>
                <vro.auth>vra</vro.auth>
                <vro.tenant>vsphere.local</vro.tenant>
                <vro.authHost>vra-l-01a.corp.local</vro.authHost>
                <vro.authPort>443</vro.authPort>
                <vrang.host>vra-l-01a.corp.local</vrang.host>
                <vrang.auth.host>vra-l-01a.corp.local</vrang.auth.host>
                <vrang.serverId>vro</vrang.serverId>
                <vrang.port>443</vrang.port>
                <vrang.project.name>vRBT</vrang.project.name>
                <vrealize.ssl.ignore.hostname>true</vrealize.ssl.ignore.hostname>
                <vrealize.ssl.ignore.certificate>true</vrealize.ssl.ignore.certificate>
            </properties>
        </profile>
    </profiles>
</settings>
```

**Comment by VenelinBakalov** [comment]
Hi @ssnui , I see there has been some discussion on this topic and it is quite old. The last answer provided by @Michaelpalacce should help you with your issue. If it does not, feel free to re-open the current issue and continue the discussion.
