### ISSUE TITLE
Use lazy loading of API Explorer categories - VRAE-51997

### ISSUE THREAD

**Issue by vivekmandal** [vmware/vrealize-developer-tools#137]
### Description

vRBT Tool Explorer Tries to load all the Pacakgs/Actions from the vRO. It tries to execute multiple API calls to extract the categories.

Eg. /vco/api/server-configuration/api/category/8a74829777f3608f01785e04fddd143c

This leads in multiple vRO crashes. The vro services gets rebooted.

### Related issues and PRs

A GSS Ticket was raised for the same issue. They asked to file a bug with the above title.

**Comment by VenelinBakalov** [comment]
Closed with https://github.com/vmware/vrealize-developer-tools/pull/142
