### ISSUE TITLE
Allow vrdev.buildTools.defaultVersion to be overridden by .vscode/settings.json

### ISSUE THREAD

**Issue by Indy-rbo** [vmware/vrealize-developer-tools#154]
### Description

In #10 the setting `vrdev.buildTools.defaultVersion` was added with the scope of `application`. https://github.com/vmware/vrealize-developer-tools/blob/fb54b055807411db293062135db23f796a8ad0ca/package.json#L507

I would like this scope to be set to something which allows it to be overridden in `.vscode/settings.json` (like `workspace`?). So that all team members have it set to the same version.

It currently shows the following message when I want to override it:

![image](https://github.com/user-attachments/assets/2cd9710b-c769-4df6-b80b-252132540217)

**Comment by VenelinBakalov** [comment]
Hi @Indy-rbo , could you double check if this is not somehow related to another configuration of VS Code?
With the current implementation you should be able to change the setting both from the settings.json and the UI configuration of the extension:
![image](https://github.com/user-attachments/assets/5024991c-e1c7-432d-bce9-e3ce92043b10)

![image](https://github.com/user-attachments/assets/bf688691-130a-4326-97c5-77087491272d)

**Comment by VenelinBakalov** [comment]
Oh, got it, I understand now, thanks for the clarification

**Comment by VenelinBakalov** [comment]
From what I see there should be an option to change the scope to "window" which relates to the UI tab -> Workspace settings. But I am not sure if this will do the job for your case.

**Comment by VenelinBakalov** [comment]
This is what I am referring to:
User settings - Settings that apply globally to any instance of VS Code you open.
Workspace settings - Settings stored inside your workspace and only apply when the workspace is opened.

https://code.visualstudio.com/docs/getstarted/settings

**Comment by VenelinBakalov** [comment]
If we change the scope to Window, the result is that you have the default setting set up on your workspace with the option to override it with user setting:
![image](https://github.com/user-attachments/assets/2202128c-3818-47de-8847-cb2eb1755b1d)

![image](https://github.com/user-attachments/assets/b6cafcee-6fe4-49d1-8748-84ab0d3318a8)

But if you change it for one Workspace (or one instance on VS code) it will not affect other instances that you open before or after that.

**Comment by Indy-rbo** [comment]
I'm not sure if the last part about not affecting other instances is a big downside?

Looking at https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema (and scrolling down to the scope header) also shows the scope `resource` with the description: `Resource settings, which apply to files and folders, and can be configured in all settings levels, even folder settings.`

I'm not well versed in VSCode extensions, but I've seen other extensions use this scope which worked for us. I can't recommend what scope would be the best, as long as I could override it in the workspace 😅

**Comment by VenelinBakalov** [comment]
Hmm will try those to see how they behave. Regarding the window scope, on my side this is fine, my question was more in the direction whether that would work for you?
If you have the time, change the scope locally to "window", run "gulp package" to package the extension, install the packaged snapshot version manually from Install from VSIX option, reload the window and test if that option works well for your case. I will check the other suggested scope options.
![image](https://github.com/user-attachments/assets/3b6bf712-c1bb-4f26-9894-fb822c4fec9d)

**Comment by VenelinBakalov** [comment]
I tried the different settings suggested, machine-overridable and resource truly seem the most flexible - you have both user and workspace settings plus the option for local file that takes highest precedence. Once you start removing those options one by one, the next in line takes precedence (removing the local file, leaving the UI setting empty, removing the setting from the users settings.json and so on).

**Comment by Indy-rbo** [comment]
Yes I agree that `resource` is likely the most fitting scope. This direction would work for us :)

**Comment by Indy-rbo** [comment]
Hi @VenelinBakalov thanks again for fixing this so quickly!
We'd like to use this. Could you possibly give an indication as to when this extension update gets released? :)

**Comment by VenelinBakalov** [comment]
Hi @Indy-rbo , since you need this feature we should be able to release this week. I will keep you posted.

**Comment by VenelinBakalov** [comment]
Everything went fine, 2.5.5 is now available in the marketplace: https://marketplace.visualstudio.com/manage/publishers/vmware-pscoe
Setting should now be available with the new scope :) thanks for the help with this one!

**Comment by Indy-rbo** [comment]
Happy to help. Thanks for the quick release as well!
