### ISSUE TITLE
Split VroRestClient into multiple classes by vRO service

### ISSUE THREAD

**Issue by krisdimitrov** [vmware/vrealize-developer-tools#45]
Split this class into multiple smaller classes by vRO service.

For example:
- VroRestActionsClient
- vRORestPluginsClient
and etc.

_Originally posted by @krisdimitrov in https://github.com/vmware/vrealize-developer-tools/pull/42_

**Comment by VenelinBakalov** [comment]
Synced internally that this enhancement will introduce more issues than benefits and is descoped.
