### ISSUE TITLE
vrealize developer tools for vRA8?

### ISSUE THREAD

**Issue by safeaim** [vmware/vrealize-developer-tools#52]
Is this project meant primarily for developing around vRA 7.6 or will it also be relevant for vRA8?

**Comment by nblagoev** [comment]
vRA 8 still has vRO as extensibility mechanism, so yes vRealize Developer Tools will be relevant for it as well. 😃 

The upcoming version of [vRealize Build Tools](https://flings.vmware.com/vrealize-build-tools) will also have support for vRA 8 projects.

**Comment by safeaim** [comment]
That's great to hear :-) Keep up the good work!
