### ISSUE TITLE
[request] is it possible to use an HTTP proxy to get to the vRA and vRO systems?

### ISSUE THREAD

**Issue by febs** [vmware/vrealize-developer-tools#56]
This is a request and not an issue. I could not find it in the documentation, I apologize it is mentioned.

The subject says it all: are there any settings.xml tags to configure the connections through an HTTP (or eventually SOCKS) proxy?

Thanks,

**Comment by kgkolev** [comment]
You can check https://maven.apache.org/guides/mini/guide-proxies.html for info how to enable maven to access vRA/vRO/Artifactory endpoints through the proxy you configure.

For VSCode, you would have to append the proxy settings to command line. More details here: https://code.visualstudio.com/docs/setup/network#_proxy-server-support

**Comment by febs** [comment]
Thank you @kgkolev.
I was actually patching the source code so to be able to use a proxy in the configuration file (I just created a different request object when proxy options were found) but that's easier.

I can't still use this tool anyways because we run vRA 7.6 as per https://github.com/vmware/vrealize-developer-tools/issues/48

Thanks, will wait for that to happen (I might give it a try though).
