### ISSUE TITLE
When using the vRealize Build Tools with vRO 7.6 the Action Version history is incorrect

### ISSUE THREAD

**Issue by netgeekmdc** [vmware/vrealize-developer-tools#71]
### Description
When Building an action with Maven and deploying it to a 7.6 vRO the Action Version history tab appears to be incorrect (It shows an older version of the script in the current version in the diff section).  Looking at the Script tab shows the correct javascript that was pushed with the build.  If I manually update the Action in the vRO Client the Version history is correct and matches what is shown on the Script tab

### Steps to Reproduce

1. Develop an Action in VsCode
2. Build / Deploy with Maven
3. Review the Action in the vRO UI (Compare the Script Tab with the Version Tab)
4. Make a change to the code in VsCode
5. Build / Deploy with Maven
6. Review the Action in the vRO webui (Compare the Script Tab with the Version Tab)
7. I see that they are different

**Expected behavior:** [What you expect to happen]
In the vRO WebUI I expect that what is displayed in the Script tab of an Action deployed with Maven matches the top version in the Version History Tab.

**Actual behavior:** [What actually happens]
In the vRO WebUI the Script tab of the Action deployed with Maven does not match the top version in the Version History Yab.

**Reproduces how often:** 
100%

### Environment
Linux Server building using Jenkins executing Maven using vRealize Build tools v2.4.18 

#### Client

-   vRealize Developer Tools Version: 2.1.6
-   vRealize Build Tools Version: v2.4.18 
-   VSCode Version: 1.45.1
-   OS Version: Ubuntu 18.04.4

#### Server

-   vRealize Automation Version: 
-   vRealize Orchestrator Version: 7.6

### Failure Logs
 It does not fail, I am deploying this via Maven on a linux server.

### Additional Context
Workflow is as follows:

- Use VsCode on my local workstation to make changes to an Action
- Push the code to a git repository
- Jenkins kicks off a build
- Maven is executed that performs the build/test and deploy to the vRO server
- Review the action in the target vRO
-- Script tab shows a different script than what is displayed in the Version History tab

**Comment by VenelinBakalov** [comment]
Hi @netgeekmdc .
I tried covering your test scenario but everything seems to be ok with the script. The new part of the script gets pushed both in the "Script" section of the action and then "Version History" section and the latest code is populated in both. Maybe it was related to some issue that existed in an earlier version of Build Tools for Aria

![image](https://github.com/vmware/vrealize-developer-tools/assets/22296648/434cc13d-cc53-44bf-9254-00e875748e2d)

Could you try re-executing with some of the newer versions like 2.38.1?

And just to make sure that I understood you correctly, the tests above cover script update and difference in the script itself. If you are referring to the version number (in my case 1.0.0) it is entirely controlled by the version defined in your pom file (basically the vRO package version) and only gets updated if that value changes.
![image](https://github.com/vmware/vrealize-developer-tools/assets/22296648/6423689a-ff96-496e-a921-a72723b91a54)


Feel free to re-open the issue if you still encounter difficulties.
