### ISSUE TITLE
EBS vrealize:push fails with 'content type does not exist'

### ISSUE THREAD

**Issue by cbazavan** [vmware/vrealize-developer-tools#78]
### Description

Using Jenkins and Maven (vrealize:push goal), we are able to successfully get vRA&vRO content imported in our target systems and it is working well with: property-group, property-definition, software-component, composite-blueprint, xaas-*. 

We are trying to use the same setup to push a vra package that contains EBS subscriptions. According to the documentation available in the downloadable archive, the supported content should be one in:

- property-group:
- property-definition:
- software-component:
- composite-blueprint:
- xaas-blueprint:
- xaas-resource-action:
- xaas-resource-type:
- xaas-resource-mapping:
- workflow-subscription:
- global-property-group:
- global-property-definition:

Attempting to use **workflow-subscription** in the package directory structure and placing an exported subscription inside of it does not work, as the push job fails.

### Steps to Reproduce

1. Create a vRA package with structure like:
`.
├── content.yaml
├── pom.xml
└── src
    └── main
        └── resources
            ├── metadata.yaml
            ├── xaas-resource-action
            │   ├── 16afaf0a-4723-4d91-a1d4-10861f9d7e9b.yaml
            ├── xaas-resource-mapping
            │   └── 7678c331-32eb-470b-8cdb-01675f30bc7d.yaml
            └── xaas-resource-type
            │   └── 1e0bd166-6d02-40fc-baa7-d8d8f4836b07.yaml
            └── workflow-subscription
`
2. run `mvn package vrealize:push -P<configured profile>`

**Expected behavior:** maven run is successful

**Actual behavior:** maven run fails with (error coming as response from vRA endpoint)
`
"operationErrors": [
         {
           "errorCode": 85507,
           "errorMessage": "85507-The content type [workflow-subscription] does not exist."
         }
       ]

`

**Reproduces how often:** 100%

#### Client

-   vRealize Developer Tools Version: 2.1.6
-   vRealize Build Tools Version: 2.4.18
-   VSCode Version: -
-   OS Version: -

#### Server

-   vRealize Automation Version: 7.5
-   vRealize Orchestrator Version: 7.5

### Failure Logs

"operationErrors": [
         {
           "errorCode": 85507,
           "errorMessage": "85507-The content type [workflow-subscription] does not exist."
         }
       ]

### Related issues and PRs

None
### Additional Context

None

**Comment by tsimchev** [comment]
Hi @cbazavan ,

What is the version of vRBT you are using?
Could you be able to share the package contents?

I also see that there is no content in the folder `workflow-subscription` under 'Create a vRA package with a structure like'

Regards,
Teo

**Comment by cbazavan** [comment]
Hi @tsimchev ,

I have updated the version of vRBT in description. I also realized that I was a version behind and I updated, but the behavior can be replicated on the latest version as well.

I attached the exported subscription that we attempted to use (place that under workflow-subscription directory), but the content is irrelevant, as I've tried in multiple scenarios (different content, invalid file, empty file, no file, JSON file) and the answer from vRA endpoint is always the same, it doesn't recognize the `workflow-subscription` directory as a content type. 
The question that I have would be: do you have any suggestion about how the directory structure would look like so it is valid for uploading to vRA? ie. how the directory should be called, the naming of the EBS exported file, the type of file used?

Thank you very much for your time.

Regards,
Catalin
[content-event-test.zip](https://github.com/vmware/vrealize-developer-tools/files/5128366/content-event-test.zip)

**Comment by tsimchev** [comment]
Hi Catlin,

Unfortunately we are not able to reproduce your issue. Attached is a working version, could you give it a try and probably include your subscription inside.

[subscription-test.zip](https://github.com/vmware/vrealize-developer-tools/files/5282521/subscription-test.zip)

Cheers,
Teo

**Comment by pe1pip** [comment]
I found that workflow-subscriptions cannot be the only thing in a package. If you have something else (I added a property definition I believe) you can pull the package.

**Comment by VenelinBakalov** [comment]
Hi @cbazavan , have you had a chance to test the package from @tsimchev ? Are you still facing the issue?

**Comment by VenelinBakalov** [comment]
I see that there is no new feedback regarding this, feel free to re-open the issue if it still applies.
