### ISSUE TITLE
Add support for vRO with vRA-Cloud extensibility proxy vRO appliance using CSP auth

### ISSUE THREAD

**Issue by srlynch1** [vmware/vrealize-developer-tools#92]
### Description
As of late December 2020, a new consolidated extensibility appliance was released for vRA-Cloud with vRO 8.3 embedded.

Currently there is no documented or supported method to use the vRealize developer tools the latest vRO appliance (vRO 8.3) which is combined with the extensibility appliance, this appliance is automatically configured using **CSP auth**, so auth methods that worked (Basic) with standalone vRO appliance and vRA-Cloud no longer function.

Requesting support for auth with premise vRO (extensibility appliance) using CSP auth with vRA-Cloud, this is the only supported auth method going forward.

**Comment by VenelinBakalov** [comment]
Hi @srlynch1 , could you try to use the following properties in your settings.xml file:

<vro.auth>vra</vro.auth>
<vro.authHost>{{your vRA URL, e.g. vra-l-01a.corp.local}}</vro.authHost>

This should replace <vro.auth>basic</vro.auth> and enable you to use the new authentication options.

An alternative option you can use (if you are using the vRO for dev testing) would be to re-enable vRO basic auth:
https://docs.vmware.com/en/vRealize-Orchestrator/8.11/com.vmware.vrealize.orchestrator-install-config.doc/GUID-30026BCF-DC1F-471E-A63C-A29E85FBDD41.html

In case this does not help, feel free to re-open this issue.
